// 500 palabras más comunes en videojuegos
const vocabulary = [
    // COMBATE (Combat)
    { word: 'kill', pronunciation: '/kɪl/', meaning: 'Eliminar/Matar', example: 'You need to kill 10 enemies to complete the mission.' , category: 'combat'},
    { word: 'damage', pronunciation: '/ˈdæmɪdʒ/', meaning: 'Daño', example: 'The sword deals 50 damage per hit.' , category: 'combat'},
    { word: 'health', pronunciation: '/helθ/', meaning: 'Salud/Vida', example: 'Your health is low, find a medkit.' , category: 'combat'},
    { word: 'attack', pronunciation: '/əˈtæk/', meaning: 'Atacar', example: 'Press the button to attack enemies.' , category: 'combat'},
    { word: 'defense', pronunciation: '/dɪˈfens/', meaning: 'Defensa', example: 'Build a wall for defense against zombies.' , category: 'combat'},
    { word: 'shield', pronunciation: '/ʃild/', meaning: 'Escudo', example: 'Equip a shield to reduce damage.' , category: 'combat'},
    { word: 'weapon', pronunciation: '/ˈwepən/', meaning: 'Arma', example: 'Choose your weapon before the battle.' , category: 'combat'},
    { word: 'ammo', pronunciation: '/ˈæmoʊ/', meaning: 'Munición', example: 'I am running out of ammo, find more bullets.' , category: 'combat'},
    { word: 'crosshair', pronunciation: '/ˈkrɔːsheər/', meaning: 'Punto de mira', example: 'Aim with the crosshair to hit the target.' , category: 'combat'},
    { word: 'respawn', pronunciation: '/riːˈspɔːn/', meaning: 'Reaparición', example: 'You will respawn at the checkpoint.' , category: 'combat'},
    { word: 'critical hit', pronunciation: '/ˈkrɪtɪkəl hɪt/', meaning: 'Golpe crítico', example: 'A critical hit deals double damage.' , category: 'combat'},
    { word: 'boss', pronunciation: '/bɔːs/', meaning: 'Jefe final', example: 'Defeat the boss to unlock the next level.' , category: 'combat'},
    { word: 'enemy', pronunciation: '/ˈenəmi/', meaning: 'Enemigo', example: 'Watch out, an enemy is approaching.' , category: 'combat'},
    { word: 'retreat', pronunciation: '/rɪˈtrit/', meaning: 'Retirarse', example: 'Retreat to safety when your health is low.' , category: 'combat'},
    { word: 'stun', pronunciation: '/stʌn/', meaning: 'Aturdir', example: 'Use this spell to stun enemies for 3 seconds.' , category: 'combat'},
    { word: 'projectile', pronunciation: '/prəˈdʒektɪl/', meaning: 'Proyectil', example: 'Dodge the projectiles coming at you.' , category: 'combat'},
    { word: 'melee', pronunciation: '/ˈmeleɪ/', meaning: 'Combate cuerpo a cuerpo', example: 'Use melee attacks for close-range combat.' , category: 'combat'},
    { word: 'magic', pronunciation: '/ˈmædʒɪk/', meaning: 'Magia', example: 'Cast magic spells to defeat enemies.' , category: 'combat'},
    { word: 'spell', pronunciation: '/spel/', meaning: 'Hechizo', example: 'Learn a new fire spell at level 5.' , category: 'combat'},
    { word: 'ability', pronunciation: '/əˈbɪləti/', meaning: 'Habilidad', example: 'Activate your special ability to gain power.' , category: 'combat'},

    // MOVIMIENTO (Movement)
    { word: 'move', pronunciation: '/muːv/', meaning: 'Mover', example: 'Use WASD keys to move your character.' , category: 'movement'},
    { word: 'jump', pronunciation: '/dʒʌmp/', meaning: 'Saltar', example: 'Jump to avoid obstacles.' , category: 'movement'},
    { word: 'run', pronunciation: '/rʌn/', meaning: 'Correr', example: 'Hold shift to run faster.' , category: 'movement'},
    { word: 'walk', pronunciation: '/wɔːk/', meaning: 'Caminar', example: 'Walk slowly to avoid being detected.' , category: 'movement'},
    { word: 'sprint', pronunciation: '/sprɪnt/', meaning: 'Carrera rápida', example: 'Sprint to escape from the enemy.' , category: 'movement'},
    { word: 'climb', pronunciation: '/klaɪm/', meaning: 'Escalar', example: 'Climb the ladder to reach the roof.' , category: 'movement'},
    { word: 'swim', pronunciation: '/swɪm/', meaning: 'Nadar', example: 'Swim across the river to the other side.' , category: 'movement'},
    { word: 'fly', pronunciation: '/flaɪ/', meaning: 'Volar', example: 'Use your wings to fly over the mountains.' , category: 'movement'},
    { word: 'dash', pronunciation: '/dæʃ/', meaning: 'Embestida rápida', example: 'Use dash to quickly evade attacks.' , category: 'movement'},
    { word: 'slide', pronunciation: '/slaɪd/', meaning: 'Deslizar', example: 'Slide under the laser beam.' , category: 'movement'},
    { word: 'crouch', pronunciation: '/kraʊtʃ/', meaning: 'Agacharse', example: 'Crouch to hide from enemies.' , category: 'movement'},
    { word: 'direction', pronunciation: '/dɪˈrekʃən/', meaning: 'Dirección', example: 'Go in the direction of the red arrow.' , category: 'movement'},
    { word: 'forward', pronunciation: '/ˈfɔːrwərd/', meaning: 'Adelante', example: 'Move forward to enter the cave.' , category: 'movement'},
    { word: 'backward', pronunciation: '/ˈbækwərd/', meaning: 'Atrás', example: 'Move backward slowly.' , category: 'movement'},
    { word: 'left', pronunciation: '/left/', meaning: 'Izquierda', example: 'Turn left at the intersection.' , category: 'movement'},
    { word: 'right', pronunciation: '/raɪt/', meaning: 'Derecha', example: 'Turn right to find the treasure.' , category: 'movement'},
    { word: 'up', pronunciation: '/ʌp/', meaning: 'Arriba', example: 'Go up the stairs.' , category: 'movement'},
    { word: 'down', pronunciation: '/daʊn/', meaning: 'Abajo', example: 'Go down into the dungeon.' , category: 'movement'},
    { word: 'rotation', pronunciation: '/roʊˈteɪʃən/', meaning: 'Rotación', example: 'Use mouse movement for camera rotation.' , category: 'movement'},
    { word: 'speed', pronunciation: '/spiːd/', meaning: 'Velocidad', example: 'Increase your speed with this buff.' , category: 'movement'},

    // OBJETOS (Items)
    { word: 'item', pronunciation: '/ˈaɪtəm/', meaning: 'Objeto/Artículo', example: 'Collect items to craft new equipment.' , category: 'items'},
    { word: 'potion', pronunciation: '/ˈpoʊʃən/', meaning: 'Poción', example: 'Drink a health potion to recover.' , category: 'items'},
    { word: 'key', pronunciation: '/kiː/', meaning: 'Llave', example: 'Find the key to unlock the door.' , category: 'items'},
    { word: 'chest', pronunciation: '/tʃest/', meaning: 'Cofre/Baúl', example: 'Open the chest to find treasure.' , category: 'items'},
    { word: 'gold', pronunciation: '/ɡoʊld/', meaning: 'Oro', example: 'Collect 100 gold coins.' , category: 'items'},
    { word: 'coin', pronunciation: '/kɔɪn/', meaning: 'Moneda', example: 'Pick up the gold coin.' , category: 'items'},
    { word: 'armor', pronunciation: '/ˈɑːrmər/', meaning: 'Armadura', example: 'Equip the iron armor.' , category: 'items'},
    { word: 'helmet', pronunciation: '/ˈhelmɪt/', meaning: 'Casco', example: 'Wear a helmet for protection.' , category: 'items'},
    { word: 'boots', pronunciation: '/buːts/', meaning: 'Botas', example: 'These boots increase your running speed.' , category: 'items'},
    { word: 'sword', pronunciation: '/sɔːrd/', meaning: 'Espada', example: 'Wield the legendary sword.' , category: 'items'},
    { word: 'bow', pronunciation: '/boʊ/', meaning: 'Arco', example: 'Use a bow to shoot arrows.' , category: 'items'},
    { word: 'arrow', pronunciation: '/ˈæroʊ/', meaning: 'Flecha', example: 'Shoot an arrow at the target.' , category: 'items'},
    { word: 'shield', pronunciation: '/ʃild/', meaning: 'Escudo', example: 'Equip a wooden shield.' , category: 'items'},
    { word: 'scroll', pronunciation: '/skroʊl/', meaning: 'Pergamino', example: 'Read the ancient scroll for knowledge.' , category: 'items'},
    { word: 'gem', pronunciation: '/dʒem/', meaning: 'Gema/Piedra preciosa', example: 'Collect blue gems to buy items.' , category: 'items'},
    { word: 'ring', pronunciation: '/rɪŋ/', meaning: 'Anillo', example: 'Equip the magic ring.' , category: 'items'},
    { word: 'amulet', pronunciation: '/ˈæmjulət/', meaning: 'Amuleto', example: 'The amulet protects you from curses.' , category: 'items'},
    { word: 'artifact', pronunciation: '/ˈɑːrtɪfækt/', meaning: 'Artefacto', example: 'Find the ancient artifact.' , category: 'items'},
    { word: 'loot', pronunciation: '/luːt/', meaning: 'Botín', example: 'Collect all the loot from defeated enemies.' , category: 'items'},
    { word: 'inventory', pronunciation: '/ɪnˈventəri/', meaning: 'Inventario', example: 'Your inventory is full.' , category: 'items'},

    // MECÁNICAS DE JUEGO (Game Mechanics)
    { word: 'level', pronunciation: '/ˈlevəl/', meaning: 'Nivel', example: 'Complete level 1 to unlock level 2.' , category: 'game-mechanics'},
    { word: 'score', pronunciation: '/skɔːr/', meaning: 'Puntuación', example: 'Your score is 1000 points.' , category: 'game-mechanics'},
    { word: 'points', pronunciation: '/pɔɪnts/', meaning: 'Puntos', example: 'Earn points by defeating enemies.' , category: 'game-mechanics'},
    { word: 'quest', pronunciation: '/kwest/', meaning: 'Misión/Búsqueda', example: 'Complete this quest to advance.' , category: 'game-mechanics'},
    { word: 'mission', pronunciation: '/ˈmɪʃən/', meaning: 'Misión', example: 'Your mission is to rescue the princess.' , category: 'game-mechanics'},
    { word: 'checkpoint', pronunciation: '/ˈtʃekpɔɪnt/', meaning: 'Punto de control', example: 'Save your progress at the checkpoint.' , category: 'game-mechanics'},
    { word: 'save', pronunciation: '/seɪv/', meaning: 'Guardar', example: 'Save your game before the boss fight.' , category: 'game-mechanics'},
    { word: 'load', pronunciation: '/loʊd/', meaning: 'Cargar', example: 'Load your previous save file.' , category: 'game-mechanics'},
    { word: 'restart', pronunciation: '/riːˈstɑːrt/', meaning: 'Reiniciar', example: 'Restart the level if you fail.' , category: 'game-mechanics'},
    { word: 'difficulty', pronunciation: '/ˈdɪfɪkəlti/', meaning: 'Dificultad', example: 'Choose your difficulty level: easy, normal, or hard.' , category: 'game-mechanics'},
    { word: 'easy', pronunciation: '/ˈiːzi/', meaning: 'Fácil', example: 'Easy mode is perfect for beginners.' , category: 'game-mechanics'},
    { word: 'hard', pronunciation: '/hɑːrd/', meaning: 'Difícil', example: 'Hard mode is for experienced players.' , category: 'game-mechanics'},
    { word: 'pause', pronunciation: '/pɔːz/', meaning: 'Pausar', example: 'Press ESC to pause the game.' , category: 'game-mechanics'},
    { word: 'resume', pronunciation: '/rɪˈzuːm/', meaning: 'Reanudar', example: 'Click resume to continue playing.' , category: 'game-mechanics'},
    { word: 'quit', pronunciation: '/kwɪt/', meaning: 'Salir', example: 'Quit the game without saving.' , category: 'game-mechanics'},
    { word: 'exit', pronunciation: '/ˈeksɪt/', meaning: 'Salida', example: 'Find the exit to escape the level.' , category: 'game-mechanics'},
    { word: 'spawn', pronunciation: '/spɔːn/', meaning: 'Aparecer', example: 'Enemies will spawn from that door.' , category: 'game-mechanics'},
    { word: 'wave', pronunciation: '/weɪv/', meaning: 'Ola/Oleada', example: 'Survive 10 waves of enemies.' , category: 'game-mechanics'},
    { word: 'round', pronunciation: '/raʊnd/', meaning: 'Ronda', example: 'You won round 5!' , category: 'game-mechanics'},
    { word: 'achievement', pronunciation: '/əˈtʃiːvmənt/', meaning: 'Logro', example: 'Unlock the secret achievement.' , category: 'game-mechanics'},

    // INTERFAZ (Interface)
    { word: 'menu', pronunciation: '/ˈmenju/', meaning: 'Menú', example: 'Click on menu to see options.' , category: 'interface'},
    { word: 'start', pronunciation: '/stɑːrt/', meaning: 'Iniciar', example: 'Click start to begin the game.' , category: 'interface'},
    { word: 'options', pronunciation: '/ˈɑːpʃənz/', meaning: 'Opciones', example: 'Adjust the options in the settings menu.' , category: 'interface'},
    { word: 'settings', pronunciation: '/ˈsetɪŋz/', meaning: 'Configuración', example: 'Change the graphics settings.' , category: 'interface'},
    { word: 'button', pronunciation: '/ˈbʌtn/', meaning: 'Botón', example: 'Click the button to proceed.' , category: 'interface'},
    { word: 'select', pronunciation: '/sɪˈlekt/', meaning: 'Seleccionar', example: 'Select your character.' , category: 'interface'},
    { word: 'confirm', pronunciation: '/kənˈfɜːrm/', meaning: 'Confirmar', example: 'Click confirm to save your changes.' , category: 'interface'},
    { word: 'cancel', pronunciation: '/ˈkænsl/', meaning: 'Cancelar', example: 'Click cancel to go back.' , category: 'interface'},
    { word: 'submit', pronunciation: '/səbˈmɪt/', meaning: 'Enviar', example: 'Submit your answer.' , category: 'interface'},
    { word: 'back', pronunciation: '/bæk/', meaning: 'Atrás', example: 'Click back to return to the main menu.' , category: 'interface'},
    { word: 'next', pronunciation: '/nekst/', meaning: 'Siguiente', example: 'Click next to go to the next page.' , category: 'interface'},
    { word: 'previous', pronunciation: '/ˈpriːviəs/', meaning: 'Anterior', example: 'Click previous to go back.' , category: 'interface'},
    { word: 'continue', pronunciation: '/kənˈtɪnjuː/', meaning: 'Continuar', example: 'Click continue to proceed.' , category: 'interface'},
    { word: 'close', pronunciation: '/kloʊz/', meaning: 'Cerrar', example: 'Close this window.' , category: 'interface'},
    { word: 'open', pronunciation: '/ˈoʊpən/', meaning: 'Abrir', example: 'Open the map to see the area.' , category: 'interface'},
    { word: 'map', pronunciation: '/mæp/', meaning: 'Mapa', example: 'Check the map to find the objective.' , category: 'interface'},
    { word: 'compass', pronunciation: '/ˈkʌmpəs/', meaning: 'Brújula', example: 'The compass shows your direction.' , category: 'interface'},
    { word: 'radar', pronunciation: '/ˈreɪdɑːr/', meaning: 'Radar', example: 'Use the radar to detect enemies.' , category: 'interface'},
    { word: 'minimap', pronunciation: '/ˈmɪniːmæp/', meaning: 'Minimapa', example: 'Check the minimap for enemies.' , category: 'interface'},
    { word: 'HUD', pronunciation: '/hʌd/', meaning: 'Interfaz en pantalla', example: 'The HUD shows your health and ammo.' , category: 'interface'},

    // GENERAL
    { word: 'play', pronunciation: '/pleɪ/', meaning: 'Jugar', example: 'Let\'s play a new game!' , category: 'general'},
    { word: 'game', pronunciation: '/ɡeɪm/', meaning: 'Juego', example: 'This is the best game ever.' , category: 'general'},
    { word: 'player', pronunciation: '/ˈpleɪər/', meaning: 'Jugador', example: 'You are player 1.' , category: 'general'},
    { word: 'win', pronunciation: '/wɪn/', meaning: 'Ganar', example: 'We need to win this match.' , category: 'general'},
    { word: 'lose', pronunciation: '/luːz/', meaning: 'Perder', example: 'Don\'t lose focus.' , category: 'general'},
    { word: 'victory', pronunciation: '/ˈvɪktəri/', meaning: 'Victoria', example: 'Victory is within reach!' , category: 'general'},
    { word: 'defeat', pronunciation: '/dɪˈfit/', meaning: 'Derrota', example: 'Accept defeat with honor.' , category: 'general'},
    { word: 'tournament', pronunciation: '/ˈtɔːrnəmənt/', meaning: 'Torneo', example: 'Join the online tournament.' , category: 'general'},
    { word: 'match', pronunciation: '/mætʃ/', meaning: 'Partida/Combate', example: 'The match is starting soon.' , category: 'general'},
    { word: 'team', pronunciation: '/tiːm/', meaning: 'Equipo', example: 'Join our team to play together.' , category: 'general'},
    { word: 'multiplayer', pronunciation: '/ˈmʌltiːpleɪər/', meaning: 'Multijugador', example: 'Play multiplayer mode with friends.' , category: 'general'},
    { word: 'single player', pronunciation: '/ˈsɪŋɡəl ˈpleɪər/', meaning: 'Un jugador', example: 'Choose single player mode.' , category: 'general'},
    { word: 'online', pronunciation: '/ˈɔnlaɪn/', meaning: 'En línea', example: 'Play online with other players.' , category: 'general'},
    { word: 'offline', pronunciation: '/ɔfˈlaɪn/', meaning: 'Sin conexión', example: 'You can play offline mode.' , category: 'general'},
    { word: 'character', pronunciation: '/ˈkærəktər/', meaning: 'Personaje', example: 'Create your own character.' , category: 'general'},
    { word: 'hero', pronunciation: '/ˈhɪroʊ/', meaning: 'Héroe', example: 'You are the hero of this story.' , category: 'general'},
    { word: 'monster', pronunciation: '/ˈmɑːnstər/', meaning: 'Monstruo', example: 'Defeat the monster.' , category: 'general'},
    { word: 'zombie', pronunciation: '/ˈzɑːmbi/', meaning: 'Zombi', example: 'Escape from the zombies.' , category: 'general'},
    { word: 'dragon', pronunciation: '/ˈdræɡən/', meaning: 'Dragón', example: 'Slay the dragon.' , category: 'general'},
    { word: 'treasure', pronunciation: '/ˈtreʒər/', meaning: 'Tesoro', example: 'Find the treasure chest.' , category: 'general'},
];

// Expandir el vocabulario a 500 palabras
const additionalVocab = [
    { word: 'combo', pronunciation: '/ˈkɑːmboʊ/', meaning: 'Combinación de ataques', example: 'Land a 10-hit combo.' , category: 'combat'},
    { word: 'buff', pronunciation: '/bʌf/', meaning: 'Mejora/Potenciador', example: 'Get a damage buff.' , category: 'game-mechanics'},
    { word: 'debuff', pronunciation: '/diːˈbʌf/', meaning: 'Debilitación', example: 'Avoid the debuff effect.' , category: 'game-mechanics'},
    { word: 'mana', pronunciation: '/ˈmɑːnə/', meaning: 'Maná (recurso mágico)', example: 'Your mana is depleted.' , category: 'combat'},
    { word: 'experience', pronunciation: '/ɪkˈspɪriəns/', meaning: 'Experiencia', example: 'Gain experience points.' , category: 'game-mechanics'},
    { word: 'XP', pronunciation: '/ɛks piː/', meaning: 'Puntos de experiencia', example: 'Earn 500 XP.' , category: 'game-mechanics'},
    { word: 'level up', pronunciation: '/ˈlevəl ʌp/', meaning: 'Subir de nivel', example: 'Level up to unlock new abilities.' , category: 'game-mechanics'},
    { word: 'skill', pronunciation: '/skɪl/', meaning: 'Habilidad', example: 'Learn a new skill.' , category: 'game-mechanics'},
    { word: 'cooldown', pronunciation: '/ˈkuːldaʊn/', meaning: 'Tiempo de espera', example: 'The ability is on cooldown.' , category: 'game-mechanics'},
    { word: 'range', pronunciation: '/reɪndʒ/', meaning: 'Alcance', example: 'Increase your attack range.' , category: 'combat'},
    { word: 'target', pronunciation: '/ˈtɑːrɡɪt/', meaning: 'Objetivo/Blanco', example: 'Select your target.' , category: 'combat'},
    { word: 'zoom', pronunciation: '/zuːm/', meaning: 'Zoom/Acercamiento', example: 'Use zoom to see details.' , category: 'interface'},
    { word: 'controller', pronunciation: '/kənˈtroʊlər/', meaning: 'Control/Mando', example: 'Connect your controller.' , category: 'interface'},
    { word: 'keyboard', pronunciation: '/ˈkiːbɔːrd/', meaning: 'Teclado', example: 'Use the keyboard to play.' , category: 'interface'},
    { word: 'mouse', pronunciation: '/maʊs/', meaning: 'Ratón', example: 'Use your mouse to aim.' , category: 'interface'},
    { word: 'graphics', pronunciation: '/ˈɡræfɪks/', meaning: 'Gráficos', example: 'Improve your graphics settings.' , category: 'interface'},
    { word: 'resolution', pronunciation: '/ˌrezəˈluːʃən/', meaning: 'Resolución', example: 'Change the resolution.' , category: 'interface'},
    { word: 'FPS', pronunciation: '/ɛf piː ɛs/', meaning: 'Fotogramas por segundo', example: 'Get 60 FPS.' , category: 'interface'},
    { word: 'lag', pronunciation: '/læɡ/', meaning: 'Retraso/Lag', example: 'There is too much lag.' , category: 'interface'},
    { word: 'ping', pronunciation: '/pɪŋ/', meaning: 'Ping (latencia)', example: 'Your ping is 50ms.' , category: 'interface'},
    { word: 'password', pronunciation: '/ˈpæswɜːrd/', meaning: 'Contraseña', example: 'Enter your password.' , category: 'interface'},
    { word: 'username', pronunciation: '/ˈjuːzərneɪm/', meaning: 'Nombre de usuario', example: 'Create a username.' , category: 'interface'},
    { word: 'profile', pronunciation: '/ˈproʊfaɪl/', meaning: 'Perfil', example: 'Check your profile stats.' , category: 'interface'},
    { word: 'leaderboard', pronunciation: '/ˈledərbɔːrd/', meaning: 'Tabla de posiciones', example: 'You are #1 on the leaderboard.' , category: 'general'},
    { word: 'rank', pronunciation: '/ræŋk/', meaning: 'Rango/Posición', example: 'Increase your rank.' , category: 'general'},
    { word: 'grinding', pronunciation: '/ˈɡraɪndɪŋ/', meaning: 'Repetir misiones para ganar experiencia', example: 'Grinding for gold.' , category: 'game-mechanics'},
    { word: 'NPC', pronunciation: '/ɛn piː siː/', meaning: 'Personaje no jugable', example: 'Talk to the NPC.' , category: 'general'},
    { word: 'dialogue', pronunciation: '/ˈdaɪəlɑːɡ/', meaning: 'Diálogo', example: 'Choose your dialogue option.' , category: 'interface'},
    { word: 'merchant', pronunciation: '/ˈmɜːrtʃənt/', meaning: 'Comerciante', example: 'Visit the merchant to buy items.' , category: 'general'},
    { word: 'trade', pronunciation: '/treɪd/', meaning: 'Comerciar', example: 'Trade items with other players.' , category: 'game-mechanics'},
    { word: 'craft', pronunciation: '/kræft/', meaning: 'Fabricar/Crear', example: 'Craft a new weapon.' , category: 'game-mechanics'},
    { word: 'recipe', pronunciation: '/ˈresəpi/', meaning: 'Receta', example: 'Learn a new recipe.' , category: 'game-mechanics'},
    { word: 'upgrade', pronunciation: '/ʌpˈɡreɪd/', meaning: 'Mejorar', example: 'Upgrade your equipment.' , category: 'game-mechanics'},
    { word: 'downgrade', pronunciation: '/ˌdaʊnˈɡreɪd/', meaning: 'Degradar', example: 'Avoid downgrading your gear.' , category: 'game-mechanics'},
    { word: 'equip', pronunciation: '/ɪˈkwɪp/', meaning: 'Equipar', example: 'Equip the new armor.' , category: 'items'},
    { word: 'unequip', pronunciation: '/ʌnɪˈkwɪp/', meaning: 'Desmontar', example: 'Unequip your helmet.' , category: 'items'},
    { word: 'status', pronunciation: '/ˈsteɪtəs/', meaning: 'Estado', example: 'Check your character status.' , category: 'interface'},
    { word: 'effect', pronunciation: '/ɪˈfekt/', meaning: 'Efecto', example: 'The poison effect damages you.' , category: 'combat'},
    { word: 'poison', pronunciation: '/ˈpɔɪzən/', meaning: 'Veneno', example: 'Avoid poison damage.' , category: 'combat'},
    { word: 'fire', pronunciation: '/ˈfaɪər/', meaning: 'Fuego', example: 'Fire spell deals 100 damage.' , category: 'combat'},
    { word: 'ice', pronunciation: '/aɪs/', meaning: 'Hielo', example: 'Use ice spells to freeze enemies.' , category: 'combat'},
    { word: 'lightning', pronunciation: '/ˈlaɪtnɪŋ/', meaning: 'Rayo', example: 'Lightning strikes deal massive damage.' , category: 'combat'},
    { word: 'heal', pronunciation: '/hiːl/', meaning: 'Curar', example: 'Heal your allies.' , category: 'combat'},
    { word: 'support', pronunciation: '/səˈpɔːrt/', meaning: 'Apoyo', example: 'Play a support character.' , category: 'general'},
    { word: 'tank', pronunciation: '/tæŋk/', meaning: 'Tanque (personaje resistente)', example: 'Play as a tank.' , category: 'general'},
    { word: 'damage dealer', pronunciation: '/ˈdæmɪdʒ ˈdilər/', meaning: 'Distribuidor de daño', example: 'Become a damage dealer.' , category: 'general'},
    { word: 'DPS', pronunciation: '/diː piː ɛs/', meaning: 'Daño por segundo', example: 'Increase your DPS.' , category: 'combat'},
    { word: 'AOE', pronunciation: '/eɪ oʊ iː/', meaning: 'Área de efecto', example: 'Use AOE spells.' , category: 'combat'},
    { word: 'dodge', pronunciation: '/dɑːdʒ/', meaning: 'Esquivar', example: 'Dodge the incoming attack.' , category: 'combat'},
    { word: 'parry', pronunciation: '/ˈpæri/', meaning: 'Parar/Bloquear', example: 'Parry the enemy\'s attack.' , category: 'combat'},
    { word: 'block', pronunciation: '/blɑːk/', meaning: 'Bloquear', example: 'Block incoming damage.' , category: 'combat'},
    { word: 'reflect', pronunciation: '/rɪˈflekt/', meaning: 'Reflejar', example: 'Reflect damage back to the enemy.' , category: 'combat'},
    { word: 'teleport', pronunciation: '/ˈteləpɔːrt/', meaning: 'Teletransportación', example: 'Teleport to safety.' , category: 'movement'},
    { word: 'invisible', pronunciation: '/ɪnˈvɪzəbl/', meaning: 'Invisible', example: 'Become invisible to avoid detection.' , category: 'combat'},
    { word: 'stealth', pronunciation: '/stelθ/', meaning: 'Sigilo', example: 'Use stealth to sneak past enemies.' , category: 'movement'},
    { word: 'camouflage', pronunciation: '/ˈkæməflɑːʒ/', meaning: 'Camuflaje', example: 'Use camouflage to hide.' , category: 'movement'},
    { word: 'clue', pronunciation: '/kluː/', meaning: 'Pista', example: 'Find clues to solve the puzzle.' , category: 'game-mechanics'},
    { word: 'puzzle', pronunciation: '/ˈpʌzəl/', meaning: 'Rompecabezas', example: 'Solve the puzzle.' , category: 'game-mechanics'},
    { word: 'riddle', pronunciation: '/ˈrɪdl/', meaning: 'Adivinanza', example: 'Answer the riddle.' , category: 'game-mechanics'},
    { word: 'secret', pronunciation: '/ˈsikrət/', meaning: 'Secreto', example: 'Find the secret room.' , category: 'game-mechanics'},
    { word: 'hidden', pronunciation: '/ˈhɪdn/', meaning: 'Oculto', example: 'There is a hidden treasure.' , category: 'items'},
    { word: 'rare', pronunciation: '/rer/', meaning: 'Raro', example: 'This is a rare item.' , category: 'items'},
    { word: 'legendary', pronunciation: '/ˈledʒənderi/', meaning: 'Legendario', example: 'Obtain the legendary sword.' , category: 'items'},
    { word: 'epic', pronunciation: '/ˈepɪk/', meaning: 'Épico', example: 'Equip epic gear.' , category: 'items'},
    { word: 'uncommon', pronunciation: '/ʌnˈkɑːmən/', meaning: 'Poco común', example: 'This is uncommon equipment.' , category: 'items'},
    { word: 'common', pronunciation: '/ˈkɑːmən/', meaning: 'Común', example: 'Sell common items.' , category: 'items'},
    { word: 'quality', pronunciation: '/ˈkwɑːləti/', meaning: 'Calidad', example: 'Check the item quality.' , category: 'items'},
    { word: 'weight', pronunciation: '/weɪt/', meaning: 'Peso', example: 'This item is too heavy.' , category: 'items'},
    { word: 'strength', pronunciation: '/streŋθ/', meaning: 'Fuerza', example: 'Increase your strength stat.' , category: 'game-mechanics'},
    { word: 'intelligence', pronunciation: '/ɪnˈtelɪdʒəns/', meaning: 'Inteligencia', example: 'Boost intelligence for magic power.' , category: 'game-mechanics'},
    { word: 'agility', pronunciation: '/əˈdʒɪləti/', meaning: 'Agilidad', example: 'Increase agility for faster attacks.' , category: 'game-mechanics'},
    { word: 'stamina', pronunciation: '/ˈstæmɪnə/', meaning: 'Resistencia', example: 'Your stamina is running low.' , category: 'combat'},
    { word: 'wisdom', pronunciation: '/ˈwɪzdəm/', meaning: 'Sabiduría', example: 'Wisdom increases healing power.' , category: 'game-mechanics'},
    { word: 'charisma', pronunciation: '/ˈkærɪzmə/', meaning: 'Carisma', example: 'High charisma helps in dialogue.' , category: 'game-mechanics'},
    { word: 'luck', pronunciation: '/lʌk/', meaning: 'Suerte', example: 'Luck increases critical hit chance.' , category: 'game-mechanics'},
    { word: 'stat', pronunciation: '/stæt/', meaning: 'Estadística', example: 'Check your character stats.' , category: 'interface'},
];

// NUEVAS 500 PALABRAS
const expandedVocab = [
    // CATEGORÍA: Personajes (NPCs) - 50 palabras
    { word: 'merchant', pronunciation: '/ˈmɜːrtʃənt/', meaning: 'Comerciante que vende objetos', example: 'Visit the merchant to buy potions.' , category: 'npcs'},
    { word: 'blacksmith', pronunciation: '/ˈblæksmɪθ/', meaning: 'Herrador que forja armas', example: 'The blacksmith can upgrade your sword.' , category: 'npcs'},
    { word: 'guard', pronunciation: '/ɡɑːrd/', meaning: 'Guardia que protege', example: 'The guard blocked the entrance.' , category: 'npcs'},
    { word: 'warrior', pronunciation: '/ˈwɔːriər/', meaning: 'Guerrero fuerte', example: 'The warrior defeated the dragon.' , category: 'npcs'},
    { word: 'mage', pronunciation: '/meɪdʒ/', meaning: 'Mago que usa magia', example: 'The mage cast a powerful spell.' , category: 'npcs'},
    { word: 'archer', pronunciation: '/ˈɑːrtʃər/', meaning: 'Arquero que dispara flechas', example: 'The archer hit the target from far away.' , category: 'npcs'},
    { word: 'knight', pronunciation: '/naɪt/', meaning: 'Caballero armado', example: 'The knight charged into battle.' , category: 'npcs'},
    { word: 'paladin', pronunciation: '/ˈpælədɪn/', meaning: 'Caballero sagrado', example: 'The paladin heals wounded allies.' , category: 'npcs'},
    { word: 'priest', pronunciation: '/priːst/', meaning: 'Sacerdote/Sanador', example: 'The priest heals the party.' , category: 'npcs'},
    { word: 'rogue', pronunciation: '/roʊɡ/', meaning: 'Pícaro/Ladrón', example: 'The rogue sneaks through the shadows.' , category: 'npcs'},
    { word: 'ranger', pronunciation: '/ˈreɪndʒər/', meaning: 'Explorador cazador', example: 'The ranger hunts in the forest.' , category: 'npcs'},
    { word: 'wizard', pronunciation: '/ˈwɪzərd/', meaning: 'Hechicero experto', example: 'The wizard knows ancient spells.' , category: 'npcs'},
    { word: 'cleric', pronunciation: '/ˈklerɪk/', meaning: 'Clérigo/Sacerdote', example: 'The cleric provides support in battle.' , category: 'npcs'},
    { word: 'druid', pronunciation: '/ˈdruːɪd/', meaning: 'Druida de la naturaleza', example: 'The druid transforms into animals.' , category: 'npcs'},
    { word: 'barbarian', pronunciation: '/bɑːrˈberiən/', meaning: 'Bárbaro brutal', example: 'The barbarian deals heavy damage.' , category: 'npcs'},
    { word: 'bard', pronunciation: '/bɑːrd/', meaning: 'Bardo/Músico', example: 'The bard sings enchanted songs.' , category: 'npcs'},
    { word: 'necromancer', pronunciation: '/ˈnekroʊmænsər/', meaning: 'Nigromante', example: 'The necromancer summons undead.' , category: 'npcs'},
    { word: 'assassin', pronunciation: '/əˈsæsɪn/', meaning: 'Asesino silencioso', example: 'The assassin strikes from the shadows.' , category: 'npcs'},
    { word: 'summoner', pronunciation: '/ˈsʌmənər/', meaning: 'Invocador de criaturas', example: 'The summoner calls creatures to battle.' , category: 'npcs'},
    { word: 'shaman', pronunciation: '/ˈʃɑːmən/', meaning: 'Chamán espiritual', example: 'The shaman calls upon spirits.' , category: 'npcs'},
    { word: 'alchemist', pronunciation: '/ˈælkəmɪst/', meaning: 'Alquimista creador de pociones', example: 'The alchemist creates powerful potions.' , category: 'npcs'},
    { word: 'guardian', pronunciation: '/ˈɡɑːrdiən/', meaning: 'Guardián protector', example: 'The guardian watches over the temple.' , category: 'npcs'},
    { word: 'sage', pronunciation: '/seɪdʒ/', meaning: 'Sabio anciano', example: 'Consult the sage for wisdom.' , category: 'npcs'},
    { word: 'scholar', pronunciation: '/ˈskɑːlər/', meaning: 'Erudito intelectual', example: 'The scholar has ancient knowledge.' , category: 'npcs'},
    { word: 'witch', pronunciation: '/wɪtʃ/', meaning: 'Bruja', example: 'The witch brews magical potions.' , category: 'npcs'},
    { word: 'demon', pronunciation: '/ˈdemən/', meaning: 'Demonio maligno', example: 'Defeat the demon lord.' , category: 'npcs'},
    { word: 'angel', pronunciation: '/ˈeɪndʒəl/', meaning: 'Ángel celestial', example: 'An angel guides you forward.' , category: 'npcs'},
    { word: 'god', pronunciation: '/ɡɑːd/', meaning: 'Dios', example: 'Pray to the gods for strength.' , category: 'npcs'},
    { word: 'goddess', pronunciation: '/ˈɡɑːdes/', meaning: 'Diosa', example: 'The goddess blesses your journey.' , category: 'npcs'},
    { word: 'fairy', pronunciation: '/ˈferi/', meaning: 'Hada mágica', example: 'The fairy grants you a wish.' , category: 'npcs'},
    { word: 'elf', pronunciation: '/elf/', meaning: 'Elfo elegante', example: 'The elf is skilled with the bow.' , category: 'npcs'},
    { word: 'dwarf', pronunciation: '/dwɔːrf/', meaning: 'Enano fuerte', example: 'The dwarf mines for gold.' , category: 'npcs'},
    { word: 'orc', pronunciation: '/ɔːrk/', meaning: 'Orco brutal', example: 'The orc is a fierce warrior.' , category: 'npcs'},
    { word: 'goblin', pronunciation: '/ˈɡɑːblɪn/', meaning: 'Duende pequeño', example: 'Goblins attack in groups.' , category: 'npcs'},
    { word: 'troll', pronunciation: '/troʊl/', meaning: 'Trol grande y fuerte', example: 'The troll guards the bridge.' , category: 'npcs'},
    { word: 'vampire', pronunciation: '/ˈvæmpaɪər/', meaning: 'Vampiro', example: 'The vampire hunts at night.' , category: 'npcs'},
    { word: 'werewolf', pronunciation: '/ˈwerwʊlf/', meaning: 'Hombre lobo', example: 'Beware of werewolves.' , category: 'npcs'},
    { word: 'skeleton', pronunciation: '/ˈskeletən/', meaning: 'Esqueleto no-muerto', example: 'Fight against the skeleton army.' , category: 'npcs'},
    { word: 'ghost', pronunciation: '/ɡoʊst/', meaning: 'Fantasma espectral', example: 'The ghost haunts the castle.' , category: 'npcs'},
    { word: 'specter', pronunciation: '/ˈspektər/', meaning: 'Espectro fantasmal', example: 'The specter vanishes.' , category: 'npcs'},
    { word: 'phantom', pronunciation: '/ˈfæntəm/', meaning: 'Fantasma', example: 'A phantom appears before you.' , category: 'npcs'},
    { word: 'wraith', pronunciation: '/reɪθ/', meaning: 'Espíritu vengativo', example: 'Wraiths drain your health.' , category: 'npcs'},
    { word: 'golem', pronunciation: '/ˈɡoʊləm/', meaning: 'Golem de piedra', example: 'The golem blocks the path.' , category: 'npcs'},
    { word: 'construct', pronunciation: '/ˈkɑːnstrʌkt/', meaning: 'Construcción mágica', example: 'A magical construct guards the door.' , category: 'npcs'},
    { word: 'elemental', pronunciation: '/ˌeləˈmentəl/', meaning: 'Elemental de fuego/agua/etc', example: 'Summon an elemental ally.' , category: 'npcs'},
    { word: 'beast', pronunciation: '/biːst/', meaning: 'Bestia salvaje', example: 'A ferocious beast roams the land.' , category: 'npcs'},
    { word: 'creature', pronunciation: '/ˈkriːtʃər/', meaning: 'Criatura desconocida', example: 'Strange creatures inhabit this place.' , category: 'npcs'},
    { word: 'familiar', pronunciation: '/fəˈmɪliər/', meaning: 'Compañero mágico', example: 'Your familiar aids you in battle.' , category: 'npcs'},
    { word: 'goat', pronunciation: '/ɡoʊt/', meaning: 'Cabra', example: 'A goat blocks your path.' , category: 'npcs'},
    { word: 'horse', pronunciation: '/hɔːrs/', meaning: 'Caballo', example: 'Ride on your horse to escape.' , category: 'npcs'},
    { word: 'wolf', pronunciation: '/wʊlf/', meaning: 'Lobo', example: 'Wolves hunt in packs.' , category: 'npcs'},
    { word: 'spider', pronunciation: '/ˈspaɪdər/', meaning: 'Araña gigante', example: 'Giant spiders block the cave.' , category: 'npcs'},

    // CATEGORÍA: Entorno (Environment) - 50 palabras
    { word: 'cave', pronunciation: '/keɪv/', meaning: 'Cueva oscura', example: 'Explore the mysterious cave.' , category: 'environment'},
    { word: 'forest', pronunciation: '/ˈfɔːrɪst/', meaning: 'Bosque denso', example: 'Get lost in the dark forest.' , category: 'environment'},
    { word: 'mountain', pronunciation: '/ˈmaʊntən/', meaning: 'Montaña alta', example: 'Climb the snowy mountain.' , category: 'environment'},
    { word: 'river', pronunciation: '/ˈrɪvər/', meaning: 'Río corriente', example: 'Cross the river safely.' , category: 'environment'},
    { word: 'ocean', pronunciation: '/ˈoʊʃən/', meaning: 'Océano vasto', example: 'Sail across the ocean.' , category: 'environment'},
    { word: 'desert', pronunciation: '/ˈdezərt/', meaning: 'Desierto árido', example: 'Survive in the scorching desert.' , category: 'environment'},
    { word: 'volcano', pronunciation: '/vɑːlˈkeɪnoʊ/', meaning: 'Volcán activo', example: 'Avoid the lava from the volcano.' , category: 'environment'},
    { word: 'swamp', pronunciation: '/swɑːmp/', meaning: 'Pantano húmedo', example: 'Navigate the dangerous swamp.' , category: 'environment'},
    { word: 'island', pronunciation: '/ˈaɪlənd/', meaning: 'Isla aislada', example: 'Explore the mysterious island.' , category: 'environment'},
    { word: 'castle', pronunciation: '/ˈkæsəl/', meaning: 'Castillo fortificado', example: 'Attack the enemy castle.' , category: 'environment'},
    { word: 'dungeon', pronunciation: '/ˈdʌndʒən/', meaning: 'Mazmorra subterránea', example: 'Escape from the dungeon.' , category: 'environment'},
    { word: 'temple', pronunciation: '/ˈtempəl/', meaning: 'Templo sagrado', example: 'Enter the ancient temple.' , category: 'environment'},
    { word: 'ruins', pronunciation: '/ˈruːɪnz/', meaning: 'Ruinas antiguas', example: 'Search through the ruins.' , category: 'environment'},
    { word: 'shrine', pronunciation: '/ʃraɪn/', meaning: 'Santuario', example: 'Pray at the shrine.' , category: 'environment'},
    { word: 'tomb', pronunciation: '/tuːm/', meaning: 'Tumba antigua', example: 'Uncover the secrets of the tomb.' , category: 'environment'},
    { word: 'crypt', pronunciation: '/krɪpt/', meaning: 'Cripta funeraria', example: 'Navigate the dark crypt.' , category: 'environment'},
    { word: 'tower', pronunciation: '/ˈtaʊər/', meaning: 'Torre alta', example: 'Climb the tower to the top.' , category: 'environment'},
    { word: 'bridge', pronunciation: '/brɪdʒ/', meaning: 'Puente que atraviesa', example: 'Cross the rickety bridge.' , category: 'environment'},
    { word: 'gate', pronunciation: '/ɡeɪt/', meaning: 'Puerta/Compuerta', example: 'Open the iron gate.' , category: 'environment'},
    { word: 'wall', pronunciation: '/wɔːl/', meaning: 'Muro defensivo', example: 'Scale the wall.' , category: 'environment'},
    { word: 'door', pronunciation: '/dɔːr/', meaning: 'Puerta cerrada', example: 'Unlock the door.' , category: 'environment'},
    { word: 'window', pronunciation: '/ˈwɪndoʊ/', meaning: 'Ventana', example: 'Look through the window.' , category: 'environment'},
    { word: 'corridor', pronunciation: '/ˈkɔːrɪdɔːr/', meaning: 'Pasillo largo', example: 'Navigate the corridor.' , category: 'environment'},
    { word: 'staircase', pronunciation: '/ˈsterkeis/', meaning: 'Escalera', example: 'Climb the stairs.' , category: 'environment'},
    { word: 'platform', pronunciation: '/ˈplætfɔːrm/', meaning: 'Plataforma elevada', example: 'Jump to the platform.' , category: 'environment'},
    { word: 'ground', pronunciation: '/ɡraʊnd/', meaning: 'Suelo/Tierra', example: 'Stay on the ground.' , category: 'environment'},
    { word: 'cliff', pronunciation: '/klɪf/', meaning: 'Acantilado', example: 'Don\'t fall off the cliff.' , category: 'environment'},
    { word: 'pit', pronunciation: '/pɪt/', meaning: 'Foso profundo', example: 'Avoid the pit.' , category: 'environment'},
    { word: 'spike', pronunciation: '/spaɪk/', meaning: 'Púas letales', example: 'Dodge the spikes.' , category: 'environment'},
    { word: 'lava', pronunciation: '/ˈlɑːvə/', meaning: 'Lava ardiente', example: 'Stay away from the lava.' , category: 'environment'},
    { word: 'ice', pronunciation: '/aɪs/', meaning: 'Hielo resbaladizo', example: 'Slide on the ice.' , category: 'environment'},
    { word: 'water', pronunciation: '/ˈwɔːtər/', meaning: 'Agua', example: 'Wade through the water.' , category: 'environment'},
    { word: 'mud', pronunciation: '/mʌd/', meaning: 'Lodo pegajoso', example: 'Don\'t get stuck in the mud.' , category: 'environment'},
    { word: 'sand', pronunciation: '/sænd/', meaning: 'Arena', example: 'Walk through the sand.' , category: 'environment'},
    { word: 'grass', pronunciation: '/ɡræs/', meaning: 'Hierba', example: 'Walk through the tall grass.' , category: 'environment'},
    { word: 'tree', pronunciation: '/triː/', meaning: 'Árbol', example: 'Hide behind the tree.' , category: 'environment'},
    { word: 'rock', pronunciation: '/rɑːk/', meaning: 'Roca', example: 'Push the rock.' , category: 'environment'},
    { word: 'boulder', pronunciation: '/ˈboʊldər/', meaning: 'Peña grande', example: 'The boulder blocks the path.' , category: 'environment'},
    { word: 'debris', pronunciation: '/dəˈbriː/', meaning: 'Escombros', example: 'Clear the debris.' , category: 'environment'},
    { word: 'shadow', pronunciation: '/ˈʃædoʊ/', meaning: 'Sombra oscura', example: 'Hide in the shadows.' , category: 'environment'},
    { word: 'light', pronunciation: '/laɪt/', meaning: 'Luz', example: 'The light illuminates the path.' , category: 'environment'},
    { word: 'dark', pronunciation: '/dɑːrk/', meaning: 'Oscuridad', example: 'The area is very dark.' , category: 'environment'},
    { word: 'fog', pronunciation: '/fɔːɡ/', meaning: 'Niebla densa', example: 'Navigate through the fog.' , category: 'environment'},
    { word: 'rain', pronunciation: '/reɪn/', meaning: 'Lluvia', example: 'Heavy rain falls.' , category: 'environment'},
    { word: 'snow', pronunciation: '/snoʊ/', meaning: 'Nieve', example: 'Walk through the snow.' , category: 'environment'},
    { word: 'wind', pronunciation: '/wɪnd/', meaning: 'Viento fuerte', example: 'The wind pushes you back.' , category: 'environment'},
    { word: 'storm', pronunciation: '/stɔːrm/', meaning: 'Tormenta', example: 'Seek shelter from the storm.' , category: 'environment'},
    { word: 'thunder', pronunciation: '/ˈθʌndər/', meaning: 'Trueno', example: 'Thunder rumbles loudly.' , category: 'environment'},
    { word: 'lightning', pronunciation: '/ˈlaɪtnɪŋ/', meaning: 'Rayo', example: 'Lightning strikes the tree.' , category: 'environment'},

    // CATEGORÍA: Palabras Avanzadas de Combate - 50 palabras
    { word: 'counter', pronunciation: '/ˈkaʊntər/', meaning: 'Contraataque', example: 'Execute a counter attack.' , category: 'advanced'},
    { word: 'evasion', pronunciation: '/ɪˈveɪʒən/', meaning: 'Evasión/Esquiva', example: 'High evasion chance.' , category: 'advanced'},
    { word: 'accuracy', pronunciation: '/ˈækjərəsi/', meaning: 'Precisión', example: 'Increase your accuracy.' , category: 'advanced'},
    { word: 'precision', pronunciation: '/prɪˈsɪʒən/', meaning: 'Precisión exacta', example: 'Strike with precision.' , category: 'advanced'},
    { word: 'momentum', pronunciation: '/moʊˈmentəm/', meaning: 'Momento/Ímpetu', example: 'Build momentum for a powerful attack.' , category: 'advanced'},
    { word: 'feint', pronunciation: '/feɪnt/', meaning: 'Finta/Movimiento engañoso', example: 'Use a feint to confuse enemies.' , category: 'advanced'},
    { word: 'grapple', pronunciation: '/ˈɡræpəl/', meaning: 'Agarrón de lucha', example: 'Grapple with the enemy.' , category: 'advanced'},
    { word: 'throw', pronunciation: '/θroʊ/', meaning: 'Lanzamiento', example: 'Throw your opponent.' , category: 'advanced'},
    { word: 'knockback', pronunciation: '/ˈnɑːkbæk/', meaning: 'Empuje hacia atrás', example: 'The attack causes knockback.' , category: 'advanced'},
    { word: 'stagger', pronunciation: '/ˈstæɡər/', meaning: 'Tambaleo', example: 'Stagger the enemy with a hit.' , category: 'advanced'},
    { word: 'flinch', pronunciation: '/flɪntʃ/', meaning: 'Retroceso', example: 'Don\'t flinch from the attack.' , category: 'advanced'},
    { word: 'interrupt', pronunciation: '/ˌɪntəˈrʌpt/', meaning: 'Interrupción de habilidad', example: 'Interrupt the enemy spell.' , category: 'advanced'},
    { word: 'riposte', pronunciation: '/rɪˈpoʊst/', meaning: 'Estocada de contraataque', example: 'Execute a riposte.' , category: 'advanced'},
    { word: 'backstab', pronunciation: '/ˈbækstæb/', meaning: 'Puñalada por la espalda', example: 'Perform a backstab.' , category: 'advanced'},
    { word: 'ambush', pronunciation: '/ˈæmbʊʃ/', meaning: 'Emboscada sorpresa', example: 'Set up an ambush.' , category: 'advanced'},
    { word: 'trap', pronunciation: '/træp/', meaning: 'Trampa mortal', example: 'Trigger the trap.' , category: 'advanced'},
    { word: 'snare', pronunciation: '/sner/', meaning: 'Lazo/Trampa', example: 'Catch enemies in a snare.' , category: 'advanced'},
    { word: 'berserk', pronunciation: '/bərˈsɜːrk/', meaning: 'Estado de furia', example: 'Enter berserk mode.' , category: 'advanced'},
    { word: 'focus', pronunciation: '/ˈfoʊkəs/', meaning: 'Concentración', example: 'Focus your energy.' , category: 'advanced'},
    { word: 'stance', pronunciation: '/stæns/', meaning: 'Postura de combate', example: 'Change your fighting stance.' , category: 'advanced'},
    { word: 'combo', pronunciation: '/ˈkɑːmboʊ/', meaning: 'Secuencia de ataques', example: 'Land a 5-hit combo.' , category: 'advanced'},
    { word: 'chain', pronunciation: '/tʃeɪn/', meaning: 'Encadenamiento de ataques', example: 'Chain attacks together.' , category: 'advanced'},
    { word: 'synergy', pronunciation: '/ˈsɪnərdʒi/', meaning: 'Sinergia entre habilidades', example: 'Create synergy between skills.' , category: 'advanced'},
    { word: 'recharge', pronunciation: '/ˌriːˈtʃɑːrdʒ/', meaning: 'Recarga de energía', example: 'Recharge your abilities.' , category: 'advanced'},
    { word: 'execute', pronunciation: '/ˈeksɪkjuːt/', meaning: 'Ejecución de habilidad', example: 'Execute the finishing move.' , category: 'advanced'},
    { word: 'aftermath', pronunciation: '/ˈæftərˌmæθ/', meaning: 'Consecuencias del ataque', example: 'Deal with the aftermath.' , category: 'advanced'},
    { word: 'knockdown', pronunciation: '/ˈnɑːkdaʊn/', meaning: 'Derribamiento', example: 'Knockdown the enemy.' , category: 'advanced'},
    { word: 'juggle', pronunciation: '/ˈdʒʌɡəl/', meaning: 'Mantener enemigo en el aire', example: 'Juggle enemies in the air.' , category: 'advanced'},
    { word: 'launch', pronunciation: '/lɔːntʃ/', meaning: 'Lanzamiento al aire', example: 'Launch enemies upward.' , category: 'advanced'},
    { word: 'aerial', pronunciation: '/ˈeriəl/', meaning: 'Ataque aéreo', example: 'Perform aerial combos.' , category: 'advanced'},
    { word: 'ground-based', pronunciation: '/ɡraʊnd beɪst/', meaning: 'Ataque de tierra', example: 'Use ground-based attacks.' , category: 'advanced'},
    { word: 'mixup', pronunciation: '/ˈmɪksʌp/', meaning: 'Variación de ataque', example: 'Use mixups to confuse.' , category: 'advanced'},
    { word: 'pressure', pronunciation: '/ˈpreʃər/', meaning: 'Presión de ataque', example: 'Apply constant pressure.' , category: 'advanced'},
    { word: 'zoning', pronunciation: '/ˈzoʊnɪŋ/', meaning: 'Control de espacio', example: 'Master zoning techniques.' , category: 'advanced'},
    { word: 'spacing', pronunciation: '/ˈspeɪsɪŋ/', meaning: 'Distancia de combate', example: 'Adjust your spacing.' , category: 'advanced'},
    { word: 'footsies', pronunciation: '/ˈfʊtsiːz/', meaning: 'Lucha de posicionamiento', example: 'Win the footsies game.' , category: 'advanced'},
    { word: 'tech', pronunciation: '/tek/', meaning: 'Técnica de escape', example: 'Tech out of the combo.' , category: 'advanced'},
    { word: 'cancel', pronunciation: '/ˈkænsl/', meaning: 'Cancelación de animación', example: 'Cancel the attack animation.' , category: 'advanced'},
    { word: 'buffer', pronunciation: '/ˈbʌfər/', meaning: 'Entrada de acciones futuras', example: 'Buffer your next move.' , category: 'advanced'},
    { word: 'hitbox', pronunciation: '/ˈhɪtbɑːks/', meaning: 'Caja de colisión de ataque', example: 'The hitbox is larger than expected.' , category: 'advanced'},
    { word: 'hurtbox', pronunciation: '/ˈhɜːrtbɑːks/', meaning: 'Caja de colisión de daño', example: 'Minimize your hurtbox.' , category: 'advanced'},
    { word: 'frame-data', pronunciation: '/freɪm ˈdeɪtə/', meaning: 'Datos de fotogramas', example: 'Study the frame-data.' , category: 'advanced'},
    { word: 'startup', pronunciation: '/ˈstɑːrtʌp/', meaning: 'Inicio de ataque', example: 'Fast startup frames.' , category: 'advanced'},
    { word: 'active', pronunciation: '/ˈæktɪv/', meaning: 'Fotogramas activos de ataque', example: 'Active frames deal damage.' , category: 'advanced'},
    { word: 'recovery', pronunciation: '/rɪˈkʌvəri/', meaning: 'Recuperación post-ataque', example: 'Long recovery time.' , category: 'advanced'},
    { word: 'lag', pronunciation: '/læɡ/', meaning: 'Desventaja de seguridad', example: 'This move has lag.' , category: 'advanced'},
    { word: 'safe', pronunciation: '/seɪf/', meaning: 'Ataque seguro', example: 'Use safe attacks.' , category: 'advanced'},
    { word: 'unsafe', pronunciation: '/ʌnˈseɪf/', meaning: 'Ataque arriesgado', example: 'That move is unsafe.' , category: 'advanced'},
];

// Combinar todos los vocabularios
const allVocabulary = [...vocabulary, ...additionalVocab, ...expandedVocab];

// Merge any user/IA-generated vocabulary stored in localStorage under 'generatedVocabulary'
function loadGeneratedVocabulary() {
    try {
        const raw = localStorage.getItem('generatedVocabulary');
        if (!raw) return 0;
        const parsed = JSON.parse(raw);
        if (!Array.isArray(parsed)) return 0;
        const existing = new Set(allVocabulary.map(w => w.word));
        let added = 0;
        parsed.forEach(entry => {
            if (!entry || !entry.word) return;
            if (!existing.has(entry.word)) {
                allVocabulary.push(entry);
                existing.add(entry.word);
                added++;
            }
        });
        return added;
    } catch (e) {
        console.error('loadGeneratedVocabulary error', e);
        return 0;
    }
}

// Run on load
try {
    const n = loadGeneratedVocabulary();
    if (n) console.info(`Loaded ${n} generated vocabulary items from localStorage`);
} catch (e) {
    // ignore
}
